#Julio Montoya
# I contribute with preprocessing and EDAs creation, customization and analysis.

# -*- coding: utf-8 -*-
"""Final_Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDDQcgKZo_CJfo_OLhP1zpsfUnGYoohg
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

project_path = "/content/drive/MyDrive/NLP_Final_Project"

!ls "$project_path"

import os
os.chdir(project_path)
print("Current working directory:", os.getcwd())

import pandas as pd

df = pd.read_csv("raw_partner_headlines2.csv")
df.head()

import pandas as pd

# Path to the raw Kaggle file
path = "raw_partner_headlines2.csv"

df = pd.read_csv(path)

print("Shape (rows, columns):", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types and non-null counts:")
print(df.info())

pip install transformers torch pandas tqdm

import pandas as pd
import torch
from transformers import BertTokenizer, BertForSequenceClassification, pipeline,AutoModel
from tqdm.auto import tqdm

from transformers import AutoTokenizer, AutoModelForSequenceClassification

!nvidia-smi

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")
model = model.half().to(device)
model.eval()

label_map = model.config.id2label
print("CORRECT LABEL MAP:", label_map)

df["headline"] = df["headline"].astype(str)

# ==================================
# 2. Load FinBERT (correct mapping)
# ==================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")
model = model.half().to(device)
model.eval()

# This is the CORRECT mapping:
label_map = model.config.id2label
print("CORRECT LABEL MAP:", label_map)
# {0:'positive', 1:'negative', 2:'neutral'}

# ==================================
# 3. Fast A100 inference
# ==================================
def fast_finbert(headlines, batch_size=768):
    sentiments = []
    for i in tqdm(range(0, len(headlines), batch_size)):
        batch = headlines[i:i+batch_size]

        inputs = tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=48
        ).to(device)

        with torch.cuda.amp.autocast():
            with torch.no_grad():
                logits = model(**inputs).logits

        preds = torch.argmax(logits, dim=1).tolist()
        sentiments.extend([label_map[p] for p in preds])

    return sentiments

# ==================================
# 4. Run sentiment labeling
# ==================================
df["sentiment"] = fast_finbert(df["headline"].tolist())

# ==================================
# 5. Save corrected file
# ==================================
df.to_csv("financial_news_headlines.csv",
          index=False)

print("DONE — Corrected labels saved.")

df=pd.read_csv("financial_news_headlines.csv")
df.head(20)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

label_map = model.config.id2label
print(label_map)

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from collections import Counter
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
import numpy as np

from transformers import AutoModel

plt.rcParams["figure.figsize"] = (10, 5)
df = pd.read_csv("financial_news_headlines.csv")
print("Columns:", df.columns.tolist())
print("Number of rows:", len(df))

df["headline"] = df["headline"].astype(str)
df["date"] = pd.to_datetime(df["date"], errors="coerce")
phrasebank_path = "/content/drive/MyDrive/NLP_Final_Project/Sentences_AllAgree.txt"

df_pb = pd.read_csv(
    phrasebank_path,
    sep='@',
    header=None,
    names=['sentence', 'label'],
    engine='python',
    encoding='cp1252'
)

df_pb['sentence'] = df_pb['sentence'].astype(str).str.strip()
df_pb['label'] = df_pb['label'].astype(str).str.strip().str.lower()
print("PhraseBank rows:", len(df_pb))
print(df_pb.head())

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

finbert_name = "ProsusAI/finbert"
finbert_tokenizer = AutoTokenizer.from_pretrained(finbert_name)
finbert_model = AutoModelForSequenceClassification.from_pretrained(finbert_name)
if device.type == "cuda":
    finbert_model = finbert_model.half()
finbert_model.to(device)
finbert_model.eval()

label_map = finbert_model.config.id2label
print("FinBERT label map:", label_map)

def finbert_predict_with_probs(texts, batch_size=512, max_len=64):
    all_labels = []
    all_conf = []
    all_probs = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch = texts[i:i+batch_size]
        inputs = finbert_tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_len
        ).to(device)

        with torch.cuda.amp.autocast(enabled=(device.type=="cuda")):
            with torch.no_grad():
                logits = finbert_model(**inputs).logits

        probs = torch.softmax(logits, dim=-1)
        conf_vals, pred_ids = torch.max(probs, dim=1)

        labels = [label_map[int(i)] for i in pred_ids]
        all_labels.extend(labels)
        all_conf.extend(conf_vals.cpu().numpy().tolist())
        all_probs.extend(probs.cpu().numpy().tolist())

    return all_labels, all_conf, np.array(all_probs)

# ============================================================
# 4. Evaluate FinBERT on PhraseBank
# ============================================================
print("\nRunning FinBERT on Financial PhraseBank...")
pb_preds, pb_conf, pb_probs = finbert_predict_with_probs(df_pb["sentence"].tolist())

df_pb["finbert_label"] = pb_preds
df_pb["finbert_confidence"] = pb_conf

y_true = df_pb["label"]
y_pred = df_pb["finbert_label"]

print("\n FinBERT on PhraseBank")
print("Accuracy:", accuracy_score(y_true, y_pred))
print("\nClassification report:\n", classification_report(y_true, y_pred, digits=3))

labels_order = ["negative", "neutral", "positive"]
print("\nConfusion matrix (rows=true, cols=pred):")
print(confusion_matrix(y_true, y_pred, labels=labels_order))
print("Label order:", labels_order)

# ============================================================
# 5. Sentiment distribution comparison (PhraseBank vs your data)
# ============================================================
# Define pastel colors for each sentiment
colors = {
    "negative": "#ffb3b3",
    "neutral":  "#d9d9d9",
    "positive": "#b3d9ff"
}

# Prepare counts
pb_counts = df_pb["label"].value_counts().sort_index()
my_counts = df["sentiment"].value_counts().sort_index()

# Ensure ordering matches color dictionary
pb_colors = [colors[label] for label in pb_counts.index]
my_colors = [colors[label] for label in my_counts.index]

# Plotting
fig, axs = plt.subplots(1, 2, figsize=(12, 5))

pb_counts.plot(kind="bar", ax=axs[0], color=pb_colors)
axs[0].set_title("Financial PhraseBank Sentiment Distribution")
axs[0].set_ylabel("Count")

my_counts.plot(kind="bar", ax=axs[1], color=my_colors)
axs[1].set_title("Partner Headlines Sentiment Distribution")
axs[1].set_ylabel("Count")

plt.tight_layout()
plt.show()

# Proportions
print("\nPhraseBank distribution (proportion):")
print(pb_counts / pb_counts.sum())

print("\nDataset distribution (proportion):")
print(my_counts / my_counts.sum())


# ============================================================
# 6. Confidence score analysis on our dataset
#    Using FinBERT
# ============================================================
print("\nComputing FinBERT confidences on your dataset (this may take a bit)...")
my_preds, my_conf, my_probs = finbert_predict_with_probs(df["headline"].tolist(), batch_size=768, max_len=48)

df["finbert_pred"] = my_preds
df["confidence"] = my_conf
mismatch_rate = (df["finbert_pred"] != df["sentiment"]).mean()
print(f"\nMismatch rate between stored sentiment and fresh FinBERT preds: {mismatch_rate:.4f}")

#confidence distribution
plt.hist(df["confidence"], bins=30)
plt.title("FinBERT Confidence Distribution on Partner Headlines")
plt.xlabel("Confidence (max softmax prob)")
plt.ylabel("Frequency")
plt.show()

print("\nConfidence stats:")
print(df["confidence"].describe())

# ============================================================
# 7. Hard examples: low-confidence headlines
# ============================================================
low_conf_thr = 0.55
df_low_conf = df[df["confidence"] < low_conf_thr].copy()
print(f"\nNumber of low-confidence headlines (conf < {low_conf_thr}):", len(df_low_conf))

print("\nSample low-confidence headlines:")
print(df_low_conf[["headline", "sentiment", "confidence"]].head(10))

# ============================================================
# 8. Keyword analysis per sentiment
# ============================================================
stops = set(stopwords.words("english"))

def top_words_for_label(df_in, label, n=20):
    text = " ".join(df_in[df_in["sentiment"] == label]["headline"].astype(str)).lower()
    tokens = [w for w in text.split() if w.isalpha() and w not in stops]
    counts = Counter(tokens)
    return counts.most_common(n)

for lab in ["positive", "negative", "neutral"]:
    if lab in df["sentiment"].unique():
        print(f"\nTop words for {lab.upper()}:")
        print(top_words_for_label(df, lab, n=20))

# ============================================================
# 9. Temporal sentiment trends (monthly)
# ============================================================
df_time = df.dropna(subset=["date"]).copy()
df_time["year_month"] = df_time["date"].dt.to_period("M")

sent_by_month = df_time.groupby(["year_month", "sentiment"]).size().unstack(fill_value=0)
sent_by_month.index = sent_by_month.index.to_timestamp()

sent_by_month.plot()
plt.title("Monthly Sentiment Counts Over Time")
plt.xlabel("Month")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ============================================================
# 10. Publisher sentiment profile
# ============================================================
publisher_sent = (
    df.groupby(["publisher", "sentiment"])
      .size()
      .groupby(level=0)
      .apply(lambda x: x / x.sum())
      .unstack(fill_value=0)
)

print("\nPublisher sentiment proportions (top 10 publishers):")
print(publisher_sent.head(10))

# top 5 publishers
top_publishers = publisher_sent.index[:5]
publisher_sent.loc[top_publishers].plot(kind="bar", stacked=True)
plt.title("Sentiment Proportions by Publisher (Top 5)")
plt.ylabel("Proportion")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ============================================================
# 10. Publisher sentiment profile (clean x-axis labels)
# ============================================================

publisher_sent = (
    df.groupby(["publisher", "sentiment"])
      .size()
      .groupby(level=0)
      .apply(lambda x: x / x.sum())
      .unstack(fill_value=0)
)

# Reorder columns
publisher_sent = publisher_sent[["positive", "neutral", "negative"]]

# Rename index so plotting looks clean
publisher_sent.index.name = "publisher"

print("\nPublisher sentiment proportions (top 10 publishers):")
print(publisher_sent.head(10))

# Top 5 publishers (keep index as the name)
top_publishers = publisher_sent.iloc[:5]

pastel_colors = {
    "positive": "#b3d9ff",
    "neutral":  "#d9d9d9",
    "negative": "#ffb3b3"
}

top_publishers.plot(
    kind="bar",
    stacked=True,
    color=[pastel_colors[col] for col in top_publishers.columns],
    figsize=(12, 6)
)

plt.title("Sentiment Proportions by Publisher (Top 5)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ============================================================
# 9. Monthly Sentiment Trends (from 2009, pastel colors + thicker lines)
# ============================================================

# Ensure date is correct type
df_time = df.dropna(subset=["date"]).copy()
df_time["year_month"] = df_time["date"].dt.to_period("M")

# Filter from 2009 onward
df_time = df_time[df_time["date"].dt.year >= 2009]

# Group counts
sent_by_month = df_time.groupby(["year_month", "sentiment"]).size().unstack(fill_value=0)
sent_by_month.index = sent_by_month.index.to_timestamp()

# Pastel color map
pastel_colors = {
    "positive": "#b3d9ff",  # pastel blue
    "neutral":  "#d9d9d9",  # pastel gray
    "negative": "#ffb3b3"   # pastel red
}

# Reorder columns
sent_by_month = sent_by_month[["positive", "neutral", "negative"]]

# Plot with thicker lines (linewidth=3)
sent_by_month.plot(
    figsize=(12, 6),
    color=[pastel_colors[col] for col in sent_by_month.columns],
    linewidth=5
)

plt.title("Monthly Sentiment Counts Over Time (From 2009)")
plt.xlabel("Month")
plt.ylabel("Headline Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ============================================================
# 8B. WordCloud Visualization for Each Sentiment
# ============================================================
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Pastel color functions
def pastel_red(*args, **kwargs):
    return "#ffb3b3"

def pastel_gray(*args, **kwargs):
    return "#d9d9d9"

def pastel_blue(*args, **kwargs):
    return "#b3d9ff"

color_map = {
    "negative": pastel_red,
    "neutral": pastel_gray,
    "positive": pastel_blue
}

# Ensure text is string
df["headline"] = df["headline"].astype(str)

for sentiment in ["positive", "neutral", "negative"]:

    # Filter text
    subset = df[df["sentiment"] == sentiment]["headline"].dropna().astype(str)
    text = " ".join(subset)

    if len(text.strip()) == 0:
        print(f"No text available for sentiment: {sentiment}")
        continue

    wc = WordCloud(
        width=1200,
        height=600,
        background_color="white",
        color_func=color_map[sentiment],
        collocations=False,
        max_words=200
    ).generate(text)

    plt.figure(figsize=(12, 6))
    plt.imshow(wc, interpolation="bilinear")
    plt.title(f"Word Cloud for {sentiment.capitalize()} Headlines")
    plt.axis("off")
    plt.show()

# ============================================================
# 11. Embedding visualization (PCA) on a sample
# ============================================================
print("\nCreating embedding visualization sample...")
sample_size = 2000
df_sample = df.dropna(subset=["headline"]).sample(min(sample_size, len(df)), random_state=42)
texts_sample = df_sample["headline"].tolist()
labels_sample = df_sample["sentiment"].map({"negative":0, "neutral":1, "positive":2}).fillna(1).values

# FinBERT base model for embeddings
finbert_base = AutoModel.from_pretrained(finbert_name)
if device.type == "cuda":
    finbert_base = finbert_base.half()
finbert_base.to(device)
finbert_base.eval()

def get_embeddings(texts, batch_size=64, max_len=48):
    emb_list = []
    for i in tqdm(range(0, len(texts), batch_size)):
        batch = texts[i:i+batch_size]
        inputs = finbert_tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_len
        ).to(device)

        with torch.cuda.amp.autocast(enabled=(device.type=="cuda")):
            with torch.no_grad():
                outputs = finbert_base(**inputs)

        #sentence embedding
        cls_emb = outputs.last_hidden_state[:,0,:].detach().cpu().numpy()
        emb_list.append(cls_emb)
    return np.vstack(emb_list)

print("Computing embeddings for PCA...")
embeddings = get_embeddings(texts_sample)

print("Running PCA...")
pca = PCA(n_components=2)
coords = pca.fit_transform(embeddings)

plt.figure(figsize=(8,6))
scatter = plt.scatter(coords[:,0], coords[:,1], c=labels_sample, alpha=0.7)
plt.title("Headline Embedding Visualization (FinBERT + PCA)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

# ============================================================
# 12. Class imbalance summary
# ============================================================
print("\nClass distribution in our dataset:")
count_sent = df["sentiment"].value_counts()
print(count_sent)
print("\nProportions:")
print(count_sent / count_sent.sum())

"""Preprocessing"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Path
path = "/content/drive/MyDrive/NLP_Final_Project/financial_news_headlines.csv"
df = pd.read_csv(path)
print("Original shape:", df.shape)
print(df.head())

# Drop old index
if "Unnamed: 0" in df.columns:
    df = df.drop(columns=["Unnamed: 0"])
df["headline"] = df["headline"].astype(str).str.strip()
df["sentiment"] = df["sentiment"].str.strip().str.lower()
print("After basic cleaning:", df.shape)
df.head()

df = df.dropna(subset=["headline", "sentiment"])
df = df[df["headline"].str.len() > 0]
print("After dropping missing/empty:", df.shape)

df["len_chars"] = df["headline"].str.len()
df["len_tokens_approx"] = df["headline"].str.split().str.len()
print(df["len_tokens_approx"].describe())

label2id = {"negative": 0, "neutral": 1, "positive": 2}
id2label = {v: k for k, v in label2id.items()}

df = df[df["sentiment"].isin(label2id.keys())]
df["label_id"] = df["sentiment"].map(label2id)

print(df[["headline", "sentiment", "label_id"]].head())
df["label_id"].value_counts(normalize=True)

X = df["headline"].values
y = df["label_id"].values

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)
print("Train size:", len(X_train))
print("Val size:", len(X_val))
print("Test size:", len(X_test))

train_df = pd.DataFrame({"headline": X_train, "label_id": y_train})
val_df   = pd.DataFrame({"headline": X_val,   "label_id": y_val})
test_df  = pd.DataFrame({"headline": X_test,  "label_id": y_test})

train_df["sentiment"] = train_df["label_id"].map(id2label)
val_df["sentiment"]   = val_df["label_id"].map(id2label)
test_df["sentiment"]  = test_df["label_id"].map(id2label)

print("Train distribution:")
print(train_df["sentiment"].value_counts(normalize=True))

print("\nVal distribution:")
print(val_df["sentiment"].value_counts(normalize=True))

print("\nTest distribution:")
print(test_df["sentiment"].value_counts(normalize=True))

out_dir = "/content/drive/MyDrive/NLP_Final_Project/processed"

import os
os.makedirs(out_dir, exist_ok=True)

train_df.to_csv(f"{out_dir}/train_clean.csv", index=False)
val_df.to_csv(f"{out_dir}/val_clean.csv", index=False)
test_df.to_csv(f"{out_dir}/test_clean.csv", index=False)

print("Saved to:", out_dir)

"""Traditional Models"""

import pandas as pd

base_dir = "/content/drive/MyDrive/NLP_Final_Project/processed"

train_df = pd.read_csv(f"{base_dir}/train_clean.csv")
val_df   = pd.read_csv(f"{base_dir}/val_clean.csv")
test_df  = pd.read_csv(f"{base_dir}/test_clean.csv")

print(train_df.head(10))
print(train_df.columns)

X_train = train_df["headline"].values
y_train = train_df["label_id"].values

X_val   = val_df["headline"].values
y_val   = val_df["label_id"].values

X_test  = test_df["headline"].values
y_test  = test_df["label_id"].values

"""2Model"""

# ============================================
# TF-IDF + LR
# ============================================
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# ---- TF-IDF Vectorization ----
tfidf = TfidfVectorizer(
    max_features=50_000,
    ngram_range=(1, 2),
    lowercase=True,
    stop_words="english"
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_val_tfidf   = tfidf.transform(X_val)
X_test_tfidf  = tfidf.transform(X_test)

print("TF-IDF shapes:")
print(" Train:", X_train_tfidf.shape)
print(" Val:  ", X_val_tfidf.shape)
print(" Test: ", X_test_tfidf.shape)

target_names = ["negative", "neutral", "positive"]

# ---- Logistic Regression (baseline) ----
lr_clf = LogisticRegression(
    max_iter=1000,
    n_jobs=-1,
    solver="saga",
    multi_class="multinomial",
    class_weight="balanced",
    C=1.0
)

print("\nTraining Logistic Regression...")
lr_clf.fit(X_train_tfidf, y_train)

y_pred_lr = lr_clf.predict(X_test_tfidf)

print("\n=== Logistic Regression (TF-IDF) ===")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("\nClassification Report:\n",
      classification_report(y_test, y_pred_lr, target_names=target_names))

# ============================================
# 2) LSTM Model (slightly tuned / regularized)
# ============================================
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# ---- Tokenization & Padding ----
MAX_VOCAB = 30_000
MAX_LEN   = 30

tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq   = tokenizer.texts_to_sequences(X_val)
X_test_seq  = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding="post", truncating="post")
X_val_pad   = pad_sequences(X_val_seq,   maxlen=MAX_LEN, padding="post", truncating="post")
X_test_pad  = pad_sequences(X_test_seq,  maxlen=MAX_LEN, padding="post", truncating="post")

print("\nPadded shapes:")
print(" Train:", X_train_pad.shape)
print(" Val:  ", X_val_pad.shape)
print(" Test: ", X_test_pad.shape)

NUM_CLASSES = len(np.unique(y_train))

# ---- Class Weights (for imbalance) ----
class_weights_arr = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)
class_weights = {i: w for i, w in enumerate(class_weights_arr)}
print("\nClass weights:", class_weights)

# ---- Define a slightly smaller, more regularized BiLSTM ----
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dense, Dropout

EMBED_DIM = 100
LSTM_UNITS = 64

lstm_model = Sequential([
    Embedding(input_dim=MAX_VOCAB, output_dim=EMBED_DIM, input_length=MAX_LEN),
    Bidirectional(LSTM(LSTM_UNITS, return_sequences=False)),
    Dropout(0.4),
    Dense(64, activation="relu"),
    Dropout(0.4),
    Dense(NUM_CLASSES, activation="softmax")
])

lstm_model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    metrics=["accuracy"]
)

print("\nBiLSTM model summary:")
lstm_model.summary()

# ---- Train BiLSTM with better callbacks ----
BATCH_SIZE = 128
EPOCHS = 8

checkpoint_cb = tf.keras.callbacks.ModelCheckpoint(
    "best_lstm_model.h5",
    monitor="val_accuracy",
    save_best_only=True,
    mode="max",
    verbose=1
)

early_stopping_cb = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=2,
    restore_best_weights=True,
    verbose=1
)

history = lstm_model.fit(
    X_train_pad, y_train,
    validation_data=(X_val_pad, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    class_weight=class_weights,
    callbacks=[checkpoint_cb, early_stopping_cb],
    verbose=1
)

# ---- Evaluate BiLSTM on test set ----
y_pred_lstm_probs = lstm_model.predict(X_test_pad)
y_pred_lstm = np.argmax(y_pred_lstm_probs, axis=1)

print("\n=== BiLSTM (tuned) ===")
print("Accuracy:", accuracy_score(y_test, y_pred_lstm))
print("\nClassification Report:\n",
      classification_report(y_test, y_pred_lstm, target_names=target_names))

"""Transformer Model"""

!pip install -q --upgrade transformers accelerate datasets

import os
import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

base_dir = "/content/drive/MyDrive/NLP_Final_Project/processed"

train_df = pd.read_csv(f"{base_dir}/train_clean.csv")
val_df   = pd.read_csv(f"{base_dir}/val_clean.csv")
test_df  = pd.read_csv(f"{base_dir}/test_clean.csv")

print(train_df.head())
print(train_df["sentiment"].value_counts(normalize=True))

# Must match everything you've used so far
label2id = {"negative": 0, "neutral": 1, "positive": 2}
id2label = {v: k for k, v in label2id.items()}
target_names = ["negative", "neutral", "positive"]

# Ensure label_id exists and is int
train_df["label_id"] = train_df["label_id"].astype(int)
val_df["label_id"]   = val_df["label_id"].astype(int)
test_df["label_id"]  = test_df["label_id"].astype(int)

# For HuggingFace Datasets, rename to 'label'
train_df = train_df.rename(columns={"label_id": "label"})
val_df   = val_df.rename(columns={"label_id": "label"})
test_df  = test_df.rename(columns={"label_id": "label"})

MAX_TRAIN = 300_000   # you can increase if training time is okay
MAX_VAL   = 50_000
MAX_TEST  = 50_000

if len(train_df) > MAX_TRAIN:
    train_df = train_df.sample(MAX_TRAIN, random_state=42)

if len(val_df) > MAX_VAL:
    val_df = val_df.sample(MAX_VAL, random_state=42)

if len(test_df) > MAX_TEST:
    test_sample_df = test_df.sample(MAX_TEST, random_state=42)
else:
    test_sample_df = test_df

print("Train size:", len(train_df))
print("Val size:  ", len(val_df))
print("Test size: ", len(test_sample_df))

train_ds = Dataset.from_pandas(train_df[["headline", "label"]])
val_ds   = Dataset.from_pandas(val_df[["headline", "label"]])
test_ds  = Dataset.from_pandas(test_sample_df[["headline", "label"]])

def train_and_eval_transformer(model_name, num_epochs=3, max_length=64):
    print(f"\n==============================")
    print(f"Training model: {model_name}")
    print(f"==============================")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    def tokenize_fn(batch):
        return tokenizer(
            batch["headline"],
            truncation=True,
            padding="max_length",
            max_length=max_length
        )

    train_tok = train_ds.map(tokenize_fn, batched=True)
    val_tok   = val_ds.map(tokenize_fn, batched=True)
    test_tok  = test_ds.map(tokenize_fn, batched=True)

    # Set format for PyTorch
    train_tok = train_tok.remove_columns(["headline"])
    val_tok   = val_tok.remove_columns(["headline"])
    test_tok  = test_tok.remove_columns(["headline"])

    train_tok.set_format("torch")
    val_tok.set_format("torch")
    test_tok.set_format("torch")

    # Load model
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=3,
        label2id=label2id,
        id2label=id2label
    )

    # Training args
    safe_name = model_name.replace("/", "_")
    out_dir = f"/content/transformer_{safe_name}"

    training_args = TrainingArguments(
        output_dir=out_dir,
        evaluation_strategy="epoch",
        save_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=32,
        per_device_eval_batch_size=64,
        num_train_epochs=num_epochs,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="accuracy",
        save_total_limit=1,
        logging_steps=500,
        logging_dir=f"{out_dir}/logs",
        report_to="none"
    )

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        acc = accuracy_score(labels, preds)
        prec, rec, f1, _ = precision_recall_fscore_support(
            labels, preds, average="weighted"
        )
        return {
            "accuracy": acc,
            "f1_weighted": f1,
            "precision_weighted": prec,
            "recall_weighted": rec
        }

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_tok,
        eval_dataset=val_tok,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics
    )

    trainer.train()

    # Evaluate on test set
    test_results = trainer.predict(test_tok)
    logits = test_results.predictions
    y_true = test_results.label_ids
    y_pred = np.argmax(logits, axis=-1)

    print("\n=== Test set metrics ===")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("\nClassification report:\n",
          classification_report(y_true, y_pred, target_names=target_names))

    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "report": classification_report(y_true, y_pred, target_names=target_names, output_dict=True)
    }

"""new"""

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support

def train_and_eval_transformer(model_name, num_epochs=3, max_length=64):
    print(f"\n==============================")
    print(f"Training model: {model_name}")
    print(f"==============================")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    def tokenize_fn(batch):
        return tokenizer(
            batch["headline"],
            truncation=True,
            padding="max_length",
            max_length=max_length
        )

    # Tokenize
    train_tok = train_ds.map(tokenize_fn, batched=True)
    val_tok   = val_ds.map(tokenize_fn, batched=True)
    test_tok  = test_ds.map(tokenize_fn, batched=True)

    # Remove text column for Trainer
    train_tok = train_tok.remove_columns(["headline"])
    val_tok   = val_tok.remove_columns(["headline"])
    test_tok  = test_tok.remove_columns(["headline"])

    # Set PyTorch format
    train_tok.set_format("torch")
    val_tok.set_format("torch")
    test_tok.set_format("torch")

    # Load model
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=3,
        label2id=label2id,
        id2label=id2label
    )

    safe_name = model_name.replace("/", "_")
    out_dir = f"/content/transformer_{safe_name}"

    # IMPORTANT: No evaluation_strategy here
    training_args = TrainingArguments(
        output_dir=out_dir,
        num_train_epochs=num_epochs,
        per_device_train_batch_size=32,
        per_device_eval_batch_size=64,
        learning_rate=2e-5,
        weight_decay=0.01,
        logging_steps=500,
        logging_dir=f"{out_dir}/logs",
        report_to="none"   # avoid wandb etc.
    )

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        acc = accuracy_score(labels, preds)
        prec, rec, f1, _ = precision_recall_fscore_support(
            labels, preds, average="weighted"
        )
        return {
            "accuracy": acc,
            "f1_weighted": f1,
            "precision_weighted": prec,
            "recall_weighted": rec
        }

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_tok,
        eval_dataset=val_tok,      # used when we manually call evaluate()
        tokenizer=tokenizer,
        compute_metrics=compute_metrics
    )

    # ---- TRAIN ----
    trainer.train()

    # ---- EVALUATE ON VAL ----
    print("\n=== Validation metrics ===")
    val_results = trainer.evaluate(eval_dataset=val_tok)
    print(val_results)

    # ---- EVALUATE ON TEST ----
    print("\n=== Test set metrics ===")
    test_results = trainer.predict(test_tok)
    logits = test_results.predictions
    y_true = test_results.label_ids
    y_pred = np.argmax(logits, axis=-1)

    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("\nClassification report:\n",
          classification_report(y_true, y_pred, target_names=target_names))

    return {
        "val_results": val_results,
        "test_accuracy": accuracy_score(y_true, y_pred),
        "test_report": classification_report(
            y_true, y_pred, target_names=target_names, output_dict=True
        )
    }

model_names = [
    "distilbert-base-uncased",
    "bert-base-uncased",
    "ProsusAI/finbert"
]

all_results = {}

for m in model_names:
    metrics = train_and_eval_transformer(m, num_epochs=3)
    all_results[m] = metrics

import os
import shutil
from google.colab import drive



# 2. Define your safe "Permanent" location
project_path = "/content/drive/MyDrive/NLP_Final_Project"
models_dir = os.path.join(project_path, "models")

# Create the folder if it doesn't exist
os.makedirs(models_dir, exist_ok=True)
print(f"📂 Target Folder: {models_dir}")

# 3. List of the temporary folders created by your training function
temp_folders = [
    "transformer_distilbert-base-uncased",
    "transformer_bert-base-uncased",
    "transformer_ProsusAI_finbert"
]

# 4. Move them to safety
print("\n🚀 Starting Backup...")
for folder_name in temp_folders:
    source_path = f"/content/{folder_name}"
    dest_path = os.path.join(models_dir, folder_name)

    if os.path.exists(source_path):
        # If a version already exists in Drive, delete it so we can save the new one
        if os.path.exists(dest_path):
            shutil.rmtree(dest_path)

        shutil.move(source_path, dest_path)
        print(f"✅ SUCCESSFULLY SAVED: {folder_name}")
    else:
        # Check if it's already in Drive (maybe you moved it earlier)
        if os.path.exists(dest_path):
            print(f"ℹ️  Already saved (Source missing, but found in Drive): {folder_name}")
        else:
            print(f"❌ ERROR: Could not find {folder_name}. Did training finish?")

print("\nBackup complete. Your models are safe!")

import joblib
joblib.dump(tfidf,   os.path.join(models_dir, "tfidf_vectorizer.pkl"))
joblib.dump(lr_clf,  os.path.join(models_dir, "logreg_tfidf.pkl"))
print("Saved Logistic Regression")

# Save BiLSTM model
bilstm_path = os.path.join(models_dir, "bilstm_model.h5")
lstm_model.save(bilstm_path)
print("Saved BiLSTM model to:", bilstm_path)

# Save the Keras Tokenizer used for BiLSTM
from tensorflow.keras.preprocessing.text import tokenizer_from_json
import json

tokenizer_json = tokenizer.to_json()
with open(os.path.join(models_dir, "bilstm_tokenizer.json"), "w") as f:
    f.write(tokenizer_json)

print("Saved BiLSTM tokenizer.")

!ls "/content/drive/MyDrive/NLP_Final_Project/models"

import torch
import time
import numpy as np
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score

# 1. SETUP
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Define where your models are saved (The path from Step 1)
models_dir = "/content/drive/MyDrive/NLP_Final_Project/models"

model_map = {
    "DistilBERT": "transformer_distilbert-base-uncased",
    "BERT":       "transformer_bert-base-uncased",
    "FinBERT":    "transformer_ProsusAI_finbert"
}

models_dict = {}

#LOAD MODELS
print("\nLoading models from Google Drive...")
for display_name, folder_name in model_map.items():
    full_path = os.path.join(models_dir, folder_name)

    try:
        print(f"   Loading {display_name}...", end="")
        tokenizer = AutoTokenizer.from_pretrained(full_path)
        model = AutoModelForSequenceClassification.from_pretrained(full_path)
        model.to(device)
        model.eval()
        models_dict[display_name] = {"model": model, "tokenizer": tokenizer}
        print(" Done!")
    except Exception as e:
        print(f"\n FAILED to load {display_name} at {full_path}")
        print(f"Error: {e}")

import os
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 1. SETUP
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
models_dir = "/content/drive/MyDrive/NLP_Final_Project/models"

# Map friendly names to your folder names
model_map = {
    "DistilBERT": "transformer_distilbert-base-uncased",
    "BERT":       "transformer_bert-base-uncased",
    "FinBERT":    "transformer_ProsusAI_finbert"
}

models_dict = {}

print("⬇️  Smart-Loading models from Google Drive...")

for display_name, folder_name in model_map.items():
    base_path = os.path.join(models_dir, folder_name)

    # --- SMART CHECKPOINT FINDER ---
    # 1. Check if the folder exists
    if not os.path.exists(base_path):
        print(f"❌ MISSING: {base_path}")
        continue

    # 2. Look for "checkpoint-XXX" folders inside
    subfolders = [f for f in os.listdir(base_path) if f.startswith("checkpoint-")]

    if subfolders:
        # Sort by number (e.g., 28125 > 500) and pick the last one
        subfolders.sort(key=lambda x: int(x.split('-')[1]))
        latest_checkpoint = subfolders[-1]

        # This is the ACTUAL path to your model
        final_model_path = os.path.join(base_path, latest_checkpoint)
        print(f"   Found Checkpoints in {display_name}. Loading: {latest_checkpoint}...")
    else:
        # If no checkpoints, maybe the files are in the root (fallback)
        final_model_path = base_path
        print(f"   No sub-checkpoints found. Loading from root: {folder_name}...")

    # 3. Load the model
    try:
        tokenizer = AutoTokenizer.from_pretrained(final_model_path)
        model = AutoModelForSequenceClassification.from_pretrained(final_model_path)
        model.to(device)
        model.eval()

        models_dict[display_name] = {"model": model, "tokenizer": tokenizer}
        print(f"   ✅ Success! Loaded {display_name}")
    except Exception as e:
        print(f"   ❌ ERROR loading {display_name}: {e}")

print(f"\nReady! Loaded {len(models_dict)}/3 models.")

# ---------------------------------------------------------
# EXPERIMENT 1: THROUGHPUT (Speed Test)
# ---------------------------------------------------------
print("\n\n EXPERIMENT 1: SPEED TEST (Headlines per Second)")
print("-" * 50)

def measure_speed(model, tokenizer, texts, batch_size=32):
    # Test on 1,000 headlines
    sample = texts[:1000]
    batches = [sample[i:i+batch_size] for i in range(0, len(sample), batch_size)]

    start = time.time()
    with torch.no_grad():
        for batch in batches:
            inputs = tokenizer(batch, padding=True, truncation=True, max_length=64, return_tensors="pt").to(device)
            model(**inputs)
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    end = time.time()
    return len(sample) / (end - start)

# Use test set text
test_texts = [x['headline'] for x in test_ds]

for name, data in models_dict.items():
    speed = measure_speed(data['model'], data['tokenizer'], test_texts)
    print(f"{name:12} : {speed:.2f} headlines/sec")

# ---------------------------------------------------------
# EXPERIMENT 2: STRESS TEST (Tricky Sentences)
# ---------------------------------------------------------
print("\n\n EXPERIMENT 2: LINGUISTIC STRESS TEST")
print("-" * 50)
print("Checking how models handle contradictory financial phrasing...")

tricky_sentences = [
    "The company reported a net loss, but it was smaller than expected.",  # Positive/Neutral
    "Revenue increased 50%, but the CEO warned of supply chain issues.",  # Negative
    "Operating costs soared, eating into the profit margins.",            # Negative
    "The merger discussions have been paused indefinitely."               # Neutral/Negative
]

for text in tricky_sentences:
    print(f"\n'{text}'")
    for name, data in models_dict.items():
        inputs = data['tokenizer'](text, return_tensors="pt", truncation=True).to(device)
        with torch.no_grad():
            logits = data['model'](**inputs).logits
            probs = F.softmax(logits, dim=-1)
            pred_idx = torch.argmax(probs).item()
            conf = probs[0][pred_idx].item()

            # Map ID to Label (assuming label 0=negative, 1=neutral, 2=positive)
            # Adjust these strings if your id2label is different!
            labels = ["NEGATIVE", "NEUTRAL", "POSITIVE"]
            label_str = labels[pred_idx]

            print(f"   {name:12} -> {label_str} ({conf:.1%})")

import numpy as np
import torch
import torch.nn.functional as F
from transformers import Trainer, TrainingArguments
from sklearn.metrics import accuracy_score

print("\n\n ENSEMBLE ACCURACY")
print("-" * 50)

# --- 1. CORRECTED HELPER FUNCTION ---
def prepare_test_set(tokenizer, dataset):
    """
    Re-creates test_tok for a specific tokenizer.
    FIX: Only removes the raw text column, preserves input_ids.
    """
    def tokenize_fn(batch):
        return tokenizer(
            batch["headline"],
            truncation=True,
            padding="max_length",
            max_length=64
        )

    # 1. Apply tokenization
    tokenized = dataset.map(tokenize_fn, batched=True)

    # 2. CAREFUL REMOVAL: Only remove the raw text column "headline"
    # We must keep 'input_ids', 'attention_mask', and 'label'
    if "headline" in tokenized.column_names:
        tokenized = tokenized.remove_columns(["headline"])

    tokenized.set_format("torch")
    return tokenized

def get_probs(model, tokenizer, dataset):
    # Create the clean test set specifically for this model
    test_tok_specific = prepare_test_set(tokenizer, dataset)

    # Create a dummy trainer for prediction
    args = TrainingArguments(output_dir="tmp", per_device_eval_batch_size=64, report_to="none")
    trainer = Trainer(model=model, args=args, tokenizer=tokenizer)

    # Predict
    preds = trainer.predict(test_tok_specific)
    return F.softmax(torch.tensor(preds.predictions), dim=-1).numpy(), preds.label_ids

# --- 2. RUN ENSEMBLE ---
if len(models_dict) == 3:
    print("Calculating Ensemble predictions (Soft Voting)...")

    # Using 'test_ds' (your raw dataset variable)

    print("   -> Getting predictions from DistilBERT...")
    p1, y_true = get_probs(models_dict['DistilBERT']['model'], models_dict['DistilBERT']['tokenizer'], test_ds)

    print("   -> Getting predictions from BERT...")
    p2, _      = get_probs(models_dict['BERT']['model'],       models_dict['BERT']['tokenizer'],       test_ds)

    print("   -> Getting predictions from FinBERT...")
    p3, _      = get_probs(models_dict['FinBERT']['model'],    models_dict['FinBERT']['tokenizer'],    test_ds)

    # Average them
    avg_probs = (p1 + p2 + p3) / 3
    ensemble_preds = np.argmax(avg_probs, axis=1)

    # Individual Accuracies
    acc_distil = accuracy_score(y_true, np.argmax(p1, axis=1))
    acc_bert   = accuracy_score(y_true, np.argmax(p2, axis=1))
    acc_fin    = accuracy_score(y_true, np.argmax(p3, axis=1))
    acc_ens    = accuracy_score(y_true, ensemble_preds)

    print(f"\nDistilBERT Accuracy: {acc_distil:.5f}")
    print(f"BERT Accuracy:       {acc_bert:.5f}")
    print(f"FinBERT Accuracy:    {acc_fin:.5f}")
    print("-" * 30)
    print(f" ENSEMBLE Accuracy:  {acc_ens:.5f}")
else:
    print("Skipping Ensemble: Need all 3 models loaded.")

pip install streamlit

# Run this once to create the dummy file
import pandas as pd

data = [
    {"headline": "Apple smashes earnings expectations but warns of supply chain constraints.", "sentiment": "positive"},
    {"headline": "The merger talks have stalled indefinitely due to regulatory pushback.", "sentiment": "negative"},
    {"headline": "The Federal Reserve left interest rates unchanged at 5.25%.", "sentiment": "neutral"},
    {"headline": "Operating loss narrowed to $5 million from $12 million a year ago.", "sentiment": "positive"},
    {"headline": "CEO steps down amid allegations of accounting irregularities.", "sentiment": "negative"},
    {"headline": "Markets opened flat as investors await inflation data.", "sentiment": "neutral"},
    {"headline": "Company announces 10% workforce reduction to streamline operations.", "sentiment": "negative"},
    {"headline": "New product line expected to add $2B in revenue by Q4.", "sentiment": "positive"},
    {"headline": "Competitor's stock soared while we remained stagnant.", "sentiment": "neutral"},
    {"headline": "Despite the revenue beat, EPS missed targets by a wide margin.", "sentiment": "negative"}
]

df = pd.DataFrame(data)
df.to_csv("/content/drive/MyDrive/NLP_Final_Project/random_real_headlines.csv", index=False)
print("Created data/random_real_headlines.csv")

!wget -q -O - ipv4.icanhazip.com

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import json
# import torch
# import os
# import joblib
# 
# from transformers import AutoTokenizer, AutoModelForSequenceClassification
# st.set_page_config(page_title="Financial Sentiment Lab", page_icon="📈", layout="wide")
# # PATHS
# BASE_DIR = "/content/drive/MyDrive/NLP_Final_Project"
# MODELS_DIR = os.path.join(BASE_DIR, "models")
# 
# st.markdown("""
#     <style>
#     .sentiment-pill { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.85rem; font-weight: 700; color: white; text-transform: uppercase; }
#     .sentiment-negative { background-color: #e74c3c; }
#     .sentiment-neutral  { background-color: #95a5a6; }
#     .sentiment-positive { background-color: #27ae60; }
#     .model-card { border-radius: 10px; padding: 10px; background-color: white; border: 1px solid #e0e0e0; margin-bottom: 10px; font-size: 0.9rem; }
#     .model-title { font-weight: bold; font-size: 1rem; color: #2c3e50; margin-bottom: 5px; }
#     </style>
# """, unsafe_allow_html=True)
# 
# ID2LABEL = {0: "negative", 1: "neutral", 2: "positive"}
# @st.cache_data
# def load_data():
#     datasets = {}
#     path_project = os.path.join(BASE_DIR, "financial_news_headlines.csv")
#     path_phrase = os.path.join(BASE_DIR, "Sentences_AllAgree.txt")
#     path_random = os.path.join(BASE_DIR, "random_real_headlines.csv")
# 
#     try:
#         if os.path.exists(path_project): datasets["Project Data"] = pd.read_csv(path_project).dropna()
#         if os.path.exists(path_phrase): datasets["Financial PhraseBank"] = pd.read_csv(path_phrase, sep="@", names=["headline", "sentiment"], encoding="latin-1").dropna()
#         if os.path.exists(path_random): datasets["Real World Random"] = pd.read_csv(path_random).dropna()
#         else: datasets["Real World Random"] = pd.DataFrame([{"headline": "Market crashes.", "sentiment": "negative"}])
#     except: pass
#     return datasets
# @st.cache_resource
# def load_lr_resources():
#     try:
#         vec_path = os.path.join(MODELS_DIR, "tfidf_vectorizer.pkl")
#         model_path = os.path.join(MODELS_DIR, "logreg_tfidf.pkl")
#         if os.path.exists(vec_path) and os.path.exists(model_path):
#             return joblib.load(vec_path), joblib.load(model_path)
#         return None, None
#     except: return None, None
# 
# @st.cache_resource
# def load_transformer_model(model_folder_name):
#     base_path = os.path.join(MODELS_DIR, model_folder_name)
#     if not os.path.exists(base_path): return None, None, None
# 
#     final_path = base_path
#     if not os.path.exists(os.path.join(base_path, "config.json")):
#         subfolders = [f for f in os.listdir(base_path) if f.startswith("checkpoint-")]
#         if subfolders:
#             subfolders.sort(key=lambda x: int(x.split('-')[1]))
#             final_path = os.path.join(base_path, subfolders[-1])
#         else:
#             return None, None, None
# 
#     try:
#         tokenizer = AutoTokenizer.from_pretrained(final_path)
#         model = AutoModelForSequenceClassification.from_pretrained(final_path)
#         device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#         model.to(device)
#         model.eval()
#         return tokenizer, model, device
#     except: return None, None, None
# 
# def predict_lr(text, vec, model):
#     if not model: return "N/A", 0.0
#     try:
#         vec_text = vec.transform([text])
#         if hasattr(model, "predict_proba"):
#             probs = model.predict_proba(vec_text)[0]
#             pred_idx = np.argmax(probs)
#             return ID2LABEL[pred_idx], probs[pred_idx]
#         return "N/A", 0.0
#     except: return "Error", 0.0
# 
# def predict_transformer(text, tokenizer, model, device):
#     if not model: return "N/A", 0.0
#     try:
#         inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=64).to(device)
#         with torch.no_grad():
#             logits = model(**inputs).logits
#             probs = torch.nn.functional.softmax(logits, dim=-1)[0]
#             conf, pred_idx = torch.max(probs, dim=-1)
#         return ID2LABEL[pred_idx.item()], conf.item()
#     except: return "Error", 0.0
# 
# def get_pill_html(label):
#     if label in ["N/A", "Error"]: return '<span style="color:gray;">Not Found</span>'
#     return f'<span class="sentiment-pill sentiment-{label}">{label}</span>'
# 
# # MAIN UI
# st.sidebar.title("⚙️ Settings")
# data_map = load_data()
# 
# if not data_map:
#     st.error(f"No data found in {BASE_DIR}")
#     st.stop()
# 
# dataset_choice = st.sidebar.selectbox("Select Data", list(data_map.keys()))
# df = data_map[dataset_choice]
# if 'sentence' in df.columns: df = df.rename(columns={'sentence': 'headline'})
# if 'sentiment' not in df.columns: df['sentiment'] = 'unknown'
# 
# sample_n = st.sidebar.slider("Sample Size", 5, 50, 10)
# df_sample = df.sample(min(len(df), sample_n), random_state=42).reset_index(drop=True)
# 
# st.title("📈 news Headline Sentiment Classifier Demo APP")
# st.markdown(f"**Dataset:** {dataset_choice}")
# 
# selected_idx = st.selectbox("Choose Headline:", df_sample.index, format_func=lambda x: f"{df_sample.iloc[x]['headline'][:90]}...")
# selected_row = df_sample.iloc[selected_idx]
# st.info(f"**Headline:** {selected_row['headline']}")
# 
# with st.spinner("Loading models..."):
#     vec_lr, model_lr = load_lr_resources()
#     distil_tok, distil_model, distil_dev = load_transformer_model("transformer_distilbert-base-uncased")
#     bert_tok, bert_model, bert_dev = load_transformer_model("transformer_bert-base-uncased")
#     fin_tok, fin_model, fin_dev = load_transformer_model("transformer_ProsusAI_finbert")
# 
# c0, c1, c2, c3 = st.columns(4)
# 
# p_lr, c_lr = predict_lr(selected_row['headline'], vec_lr, model_lr)
# p_dist, c_dist = predict_transformer(selected_row['headline'], distil_tok, distil_model, distil_dev)
# p_bert, c_bert = predict_transformer(selected_row['headline'], bert_tok, bert_model, bert_dev)
# p_fin, c_fin = predict_transformer(selected_row['headline'], fin_tok, fin_model, fin_dev)
# 
# with c0: st.markdown(f"""<div class="model-card"><div class="model-title">Logistic Reg</div><div>{get_pill_html(p_lr)}</div><small>{c_lr:.1%}</small></div>""", unsafe_allow_html=True)
# with c1: st.markdown(f"""<div class="model-card"><div class="model-title">DistilBERT</div><div>{get_pill_html(p_dist)}</div><small>{c_dist:.1%}</small></div>""", unsafe_allow_html=True)
# with c2: st.markdown(f"""<div class="model-card"><div class="model-title">BERT Base</div><div>{get_pill_html(p_bert)}</div><small>{c_bert:.1%}</small></div>""", unsafe_allow_html=True)
# with c3: st.markdown(f"""<div class="model-card"><div class="model-title" style="color:#d35400">FinBERT </div><div>{get_pill_html(p_fin)}</div><small>{c_fin:.1%}</small></div>""", unsafe_allow_html=True)
# 
# if st.checkbox("Show Batch Analysis"):
#     results = []
#     for idx, row in df_sample.iterrows():
#         txt = row['headline']
#         p_lr, _ = predict_lr(txt, vec_lr, model_lr)
#         p_dist, _ = predict_transformer(txt, distil_tok, distil_model, distil_dev)
#         p_fin, _ = predict_transformer(txt, fin_tok, fin_model, fin_dev)
#         results.append({"Headline": txt, "LR": p_lr, "DistilBERT": p_dist, "FinBERT": p_fin})
#     st.dataframe(pd.DataFrame(results))

!npm install -g localtunnel
# Get your Password
print("Your Password/IP is:")
!wget -q -O - ipv4.icanhazip.com

import time
import subprocess
import os


if not os.path.exists("cloudflared"):
    !wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    !chmod +x cloudflared
print("Starting Streamlit...")
!nohup streamlit run app.py --server.port 8501 > streamlit.log 2>&1 &

print("Starting Cloudflare Tunnel...")
!nohup ./cloudflared tunnel --url http://localhost:8501 > tunnel.log 2>&1 &

time.sleep(8)
print("\n CLICK THE LINK BELOW TO OPEN YOUR APP:\n")
!grep -o 'https://.*\.trycloudflare.com' tunnel.log